### ISSUE TITLE
Prerequisites - setuptools, pathlib

### ISSUE THREAD

**Issue by scriptzteam** [deepjyoti30/ytmdl#111]
Would be cool to mention for other that setuptools is needed and also other ?? ;)

```root@raspberrypi:~/ytmdl# sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import setuptools
ImportError: No module named setuptools
```

```
root@raspberrypi:~/ytmdl# **apt install python3-setuptools python-pathlib python3-libxml2**
```

On my raspberry pi - Linux raspberrypi 5.4.51-v7l+ #1327 SMP Thu Jul 23 11:04:39 BST 2020 armv7l GNU/Linux

```
root@raspberrypi:~/ytmdl# sudo python3 setup.py instal
Building lxml version 4.5.2.
Building without Cython.
Error: Please make sure the libxml2 and libxslt development packages are installed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-20qkarq0/lxml-4.5.2/setup.py", line 245, in <module>
  File "/tmp/easy_install-20qkarq0/lxml-4.5.2/setup.py", line 153, in setup_extra_options
  File "/tmp/easy_install-20qkarq0/lxml-4.5.2/setupinfo.py", line 113, in ext_modules
  File "/tmp/easy_install-20qkarq0/lxml-4.5.2/setupinfo.py", line 439, in check_build_dependencies
  File "/tmp/easy_install-20qkarq0/lxml-4.5.2/setupinfo.py", line 435, in get_library_versions
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-20qkarq0/lxml-4.5.2/setup.py", line 245, in <module>
  File "/tmp/easy_install-20qkarq0/lxml-4.5.2/setup.py", line 153, in setup_extra_options
  File "/tmp/easy_install-20qkarq0/lxml-4.5.2/setupinfo.py", line 113, in ext_modules
  File "/tmp/easy_install-20qkarq0/lxml-4.5.2/setupinfo.py", line 439, in check_build_dependencies
  File "/tmp/easy_install-20qkarq0/lxml-4.5.2/setupinfo.py", line 435, in get_library_versions
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    extras_require=extra_features
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 724, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 791, in fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1171, in run_setup
    raise DistutilsError("Setup script exited with %s" % (v.args[0],))
distutils.errors.DistutilsError: Setup script exited with 1```

**Comment by deepjyoti30** [comment]
@scriptzteam liblxml doesn't seem like a direct dependency so I guess the issue is not from ytmdl.

About `setuptools` I think it is required because you're installing from the `setup.py` so it is merely a dependency required for building the package and not for installing it?!

Can you try installing the package from pypi without installing `setuptools`? I guess it should be installed that way?

Regarding `pathlib` it's weird you're getting an error. I was under the impression that it is a pre installed package since it is like `os`.
