### ISSUE TITLE
Failed metadata download with LastFM

### ISSUE THREAD

**Issue by NightMean** [deepjyoti30/ytmdl#143]
# Bug report

## Checklist

- [x]  I have searched for similar bugs in the issues.
- [x]  I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2020.11.20-1`
- Youtube-dl version: `2021.01.03`

## How Ytmdl was installed?

Installed through pip.

## Console Log

```console
michal@Michal-PC:/mnt/d/Music/Album Arts/YTmdl$ ytmdl "03- The End (Simple Plan)" --level DEBUG
 ==>  Logger running in DEBUG mode
 ==>  Passed args: Namespace(SONG_NAME=['03- The End (Simple Plan)'], album=None, artist=None, choice=None, disable_file=False, disable_metaadd=False, format='mp3', get_opts=False, ignore_errors=False, level='DEBUG', list=None, list_level=False, manual_meta=False, nolocal=False, pl_end=None, pl_items=None, pl_start=None, proxy=None, quiet=False, skip_meta=False, song=None, trim=False, url=None)
 ==>  ['03- The End (Simple Plan)']
 ==>  03- The End (Simple Plan)
 ==>  Searching to see if already present in /mnt/d/Music/Album Arts/YTmdl
 ==>  proxy passed: None
 ==>  Passed format: mp3
 ==>  Searching Youtube for 03- The End (Simple Plan)
 ==> Choose One (One with [M] is verified music)
 [1] 03- The End (Simple Plan) by TheSimplePlanFanMan with dur 3:23
 [2] 03 - Simple Plan - The End (Deluxe Edition) - 2008 [HD + Lyrics] by spbestmusic with dur 3:21
 [3] [M] The End by SimplePlan with dur 3:23
 [4] 03. Simple Plan - The end [Simple Plan] by MrsPeace95 with dur 3:23
 [5] 03 The End - Simple Plan by Gv Makawili with dur 3:23
 [0] More results
 ==> Enter Choice [default is 1] 5
 ==>  {'title': '03 The End - Simple Plan', 'href': '/watch?v=SzrbQVGd3Jw', 'author_name': 'Gv Makawili', 'duration': '3:23', 'verified_music': False}
 ==>  Downloading 03 The End - Simple Plan in 192kbps
 ==>  Saving the files to: /home/michal/.cache/ytmdl
 ==>  /home/michal/.cache/ytmdl/03#The#End#-#Simple#Plan.mp3
3 MB   | 6 Mb/s || ETA: 5 s                                              |▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓| 100%
 ==>  Downloaded!
 ==>  Converting to mp3...
File '/home/michal/.cache/ytmdl/03#The#End#-#Simple#Plan.mp3_new.mp3' already exists. Overwrite ? [y/N] y
 ==>  Skip Meta: False
 ==>  Getting song data for 03- The End (Simple Plan)...
 ==>  No results found with the keyword 03- The End (Simple Plan)
 ==>  Something went wrong with iTunes. The program will continue withthe other providers. Please check 'None' for more details.
 ==> Setting data...
 ==> Choose One
 [1] 03  Simple Plan - The End by Simple Plan
 [2] Simple Plan - 03 - The End by Simple Plan
 [3] 03) The end by Simple Plan
 [4] The End (Live in São Paulo - 24/03/09) by Simple Plan
 [5] 03 03 Simple Plan - The end by Simple Plan
 [0] More results
 ==> Enter Choice [default is 1] 1
Traceback (most recent call last):
  File "/home/michal/.local/bin/ytmdl", line 469, in <module>
    extract_data()
  File "/home/michal/.local/bin/ytmdl", line 464, in extract_data
    main(args)
  File "/home/michal/.local/bin/ytmdl", line 400, in main
    option = song.setData(TRACK_INFO, is_quiet, conv_name, passed_format, choice)
  File "/home/michal/.local/lib/python3.6/site-packages/ytmdl/song.py", line 364, in setData
    song = get_more_data_dict.get(song.provider, lambda _: None)(song)
  File "/home/michal/.local/lib/python3.6/site-packages/ytmdl/meta/lastfm.py", line 64, in get_more_data
    song.collection_name = track_details["track"]["album"]["title"]
KeyError: 'album'
```

## Description

Hi, 
I enabled lastfm provider in config file to get more results but the first song I tried to download failed due to presumably missing album from lastfm. Issue can be replicated by this command: 
ytmdl "The End (Simple Plan)"

**Comment by deepjyoti30** [comment]
@NightMean Thanks for pointing out the issue. As it seems like `lastfm` has inconsistent data for some songs. Should be fixed in 446f122fcd253a82540bbeb8da06a9a2c82b003f

**Comment by NightMean** [comment]
Thanks for the update. I cloned latest version but this time I get this error.

Traceback (most recent call last):
  File "./ytmdl", line 381, in <module>
    extract_data()
  File "./ytmdl", line 376, in extract_data
    main(args)
  File "./ytmdl", line 257, in main
    track_selected = meta(conv_name, song_name, song_metadata, args)
  File "/usr/local/lib/python3.6/dist-packages/ytmdl-2020.11.20.dev0-py3.6.egg/ytmdl/core.py", line 201, in meta
  File "/usr/local/lib/python3.6/dist-packages/ytmdl-2020.11.20.dev0-py3.6.egg/ytmdl/song.py", line 367, in setData
  File "/usr/local/lib/python3.6/dist-packages/ytmdl-2020.11.20.dev0-py3.6.egg/ytmdl/meta/lastfm.py", line 64, in get_more_data
KeyError: 'album'

**Comment by deepjyoti30** [comment]
@NightMean Based on the version, seems like you installed from the `master` branch. However I made the changes to the `unstable` branch. You can wait till the changes are merged to `master` or try the `unstable` version.

**Comment by NightMean** [comment]
I apologize for the simple mistake. The fix works! :) 
On first try ytmdl did not rename the cache file in the output directory according to lastfm but after trying to replicate it for the third time I couldn't replicate it. Will make a new bug report if I manage to replicate it. I assume it was something to do with the old unrenamed file which was still there. 

Thanks for a quick fix!
