### ISSUE TITLE
[Bug] Installation failing on Gentoo

### ISSUE THREAD

**Issue by LiEyWe** [deepjyoti30/ytmdl#149]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2021.01.13`
- Youtube-dl version: `2021.01.03`

## How Ytmdl was installed?

I tried to install Ytmdl through the src_prepare-overlay.

## Console Log

```console
python3.7 setup.py build -j 9
setup.py:48: UserWarning: ytmdl.bash does not exist, skipping.
  warn("%s does not exist, skipping." % filename)
setup.py:48: UserWarning: ytmdl.zsh does not exist, skipping.
  warn("%s does not exist, skipping." % filename)
WARNING: The pip package is not available, falling back to EasyInstall for handling setup_requires/test_requires; this is deprecated and will be removed in a future version.
Download error on https://pypi.org/simple/musicbrainzngs/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
Couldn't find index page for 'musicbrainzngs' (maybe misspelled?)
Download error on https://pypi.org/simple/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
No local packages or working download links found for musicbrainzngs
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/setuptools/installer.py", line 60, in fetch_build_egg
    pkg_resources.get_distribution('pip')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 465, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 341, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    **params
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 676, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 766, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1049, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1061, in obtain
    return installer(requirement)
  File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/lib/python3.7/site-packages/setuptools/installer.py", line 68, in fetch_build_egg
    return _legacy_fetch_build_egg(dist, req)
  File "/usr/lib/python3.7/site-packages/setuptools/installer.py", line 51, in _legacy_fetch_build_egg
    return cmd.easy_install(req)
  File "/usr/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 663, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('musicbrainzngs')
```

**Comment by deepjyoti30** [comment]
@LiEyWe The gentoo source is outdated so one of the dependencies are missing. I will try to talk with the maintainer to get this updated. Thanks for reporting.

**Comment by deepjyoti30** [comment]
@xgqt Can you please take a look at this. I'm assuming you're the maintainer of `ytmdl` in the Gentoo repo's?

**Comment by xgqt** [comment]
> @xgqt Can you please take a look at this. I'm assuming you're the maintainer of `ytmdl` in the Gentoo repo's?

I will

**Comment by xgqt** [comment]
https://gitlab.com/src_prepare/src_prepare-overlay/-/commit/2d3ad33bc3c692ce566295a1192687c501b67f35

@LiEyWe please test

**Comment by LiEyWe** [comment]
> https://gitlab.com/src_prepare/src_prepare-overlay/-/commit/2d3ad33bc3c692ce566295a1192687c501b67f35
> 
> @LiEyWe please test

It works now. Thanks a lot :+1:

**Comment by xgqt** [comment]
@LiEyWe @deepjyoti30 Thanks for cooperation.
