### ISSUE TITLE
Can't install ytmdl (sudo python setup.py install)

### ISSUE THREAD

**Issue by matteog24** [deepjyoti30/ytmdl#162]
# Bug report
`sudo python setup.py` install does not work.

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## Version Info

- Ytmdl version: (can't find it since runnig `ytmdl` says the command does not exist, but it was downloaded from Git on Feb 17)
- Youtube-dl version: `stable 2021.2.10 (bottled)` (installed with Homebrew)

## How Ytmdl was installed?
`git clone https://github.com/deepjyoti30/ytmdl`
`cd ytmdl`
(setuptools was already installed, checked with `pip3 install setuptools`)

## Output log when using `sudo python setup.py` 

```console
setup.py:48: UserWarning: ytmdl.bash does not exist, skipping.
  warn("%s does not exist, skipping." % filename)
setup.py:48: UserWarning: ytmdl.zsh does not exist, skipping.
  warn("%s does not exist, skipping." % filename)
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    **params
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 717, in fetch_build_eggs
    replace_conflicting=True,
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 784, in fetch_build_egg
    return cmd.easy_install(req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 705, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 890, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1158, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/easy_install.py", line 1144, in run_setup
    run_setup(setup_script, args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-3UWE3K/youtube-search-1.1.1/setup.py", line 1, in <module>
    #!/usr/bin/env python3
ImportError: No module named pathlib
```

## Description

Everything seemed promising until I ran the command `sudo python setup.py`. Some notes:

- using macOS 10.15.7
- the user I'm using is not admin, in fact I wrote `su admin` and ran the command (otherwise it did not let me)

**Comment by deepjyoti30** [comment]
@matteog24 Seems like you have two versions of python installed. Because of that the `python` command defaults to `python2` so you'd have to go for the `python3` command.

Try installing ytmdl using `sudo python3 setup.py install`.

Also, in order to cross check if `python` is defaulting to `python2`, just run

```console
python --version
```

Above should probably print something like `python2.x`

**Comment by matteog24** [comment]
The Python version used by default is `2.7.16`, while the version 3 is `3.9.1`.

I tried the command (via admin) and it outputs several times:
<code> WARNING: The directory '/private/var/admin/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.<code>

**Comment by deepjyoti30** [comment]
@matteog24 So I was right about the issue. That warning is not related to `ytmdl`. You can look for solutions for that. However, ytmdl should be installed now.

Feel free to close the issue!

**Comment by matteog24** [comment]
I tried again and it works! Thanks!
