### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 63-65: character maps to <undefined> 'ab_channel' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by eitroo** [deepjyoti30/ytmdl#166]
# Bug report
I ran:
`ytmdl https://www.youtube.com/watch?v=JWqmJh7JNS4&ab_channel=DOVA-SYNDROMEYouTubeOfficial`
## Version Info

- Ytmdl version: 2021.1.14.post1
- Youtube-dl version: 2021.2.22

## How Ytmdl was installed?
python setuptools
## Console Log

```
Traceback (most recent call last):
  File "D:\Users\aech\AppData\Local\Programs\Python\Python36\Scripts\ytmdl", line 4, in <module>
    __import__('pkg_resources').run_script('ytmdl==2021.1.14', 'ytmdl')
  File "D:\Users\aech\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "D:\Users\aech\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\ytmdl-2021.1.14-py3.6.egg\EGG-INFO\scripts\ytmdl", line 456, in <module>
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\ytmdl-2021.1.14-py3.6.egg\EGG-INFO\scripts\ytmdl", line 451, in extract_data
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\ytmdl-2021.1.14-py3.6.egg\EGG-INFO\scripts\ytmdl", line 234, in main
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\ytmdl-2021.1.14-py3.6.egg\ytmdl\core.py", line 109, in download
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\simber\logger.py", line 338, in info
    self._write(message, args, LEVEL_NUMBER)
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\simber\logger.py", line 198, in _write
    self.name
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\simber\stream.py", line 134, in write
    print(_formatted_out, **params)
  File "D:\Users\aech\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 63-65: character maps to <undefined>
'ab_channel' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by eitroo** [comment]
python: Python 3.6.7

**Comment by deepjyoti30** [comment]
@eitroo I think I missed this when I initially looked at your example but in it you have passed the URL `https://www.youtube.com/watch?v=JWqmJh7JNS4&ab_channel=DOVA-SYNDROMEYouTubeOfficial` which also contains the `ab_channel` flag. I think that's why the error appeared.

You can just pass the above URL in the following way and it will totally work:

```console
ytmdl https://www.youtube.com/watch?v=JWqmJh7JNS4
```

**Comment by eitroo** [comment]
Still doesn't work. Here the result:
`PS C:\Users\aech\Music> ytmdl https://www.youtube.com/watch?v=JWqmJh7JNS4
 ==> Searching to see if already present in C:\Users\aech\Music
 ==> Searching Youtube for https://www.youtube.com/watch?v=JWqmJh7JNS4
 ==> Choose One (One with [M] is verified music)
 [1] Mercury Lamp @ フリーBGM DOVA-SYNDROME OFFICIAL YouTube CHANNEL by DOVA-SYNDROME YouTube Official with dur 02:42
 [2] Amelia Watson: "Bubba's 3D Debut!" by HoloLiveEN Highlights with dur 01:51
 [3] Amelia Watson 3D Dancing Bubba Outro (1 Hour Loop) by Mighty Eggroll with dur 01:00:10
 [4] Baked Scallion with Cheese  ~Japanese BBQ flavor~ / 長ねぎマヨチーズ焼き by MinaCanCooking Channel with dur 01:24
 [5] 【HoloEN】Ame's 1 Million Mini Celebration by Hololive Boubon with dur 03:09
 [0] More results
 ==> Enter Choice (1):
 ==> Downloading Mercury Lamp @ フリーBGM DOVA-SYNDROME OFFICIAL YouTube CHANNEL in 320kbps
Traceback (most recent call last):
  File "D:\Users\aech\AppData\Local\Programs\Python\Python36\Scripts\ytmdl", line 4, in <module>
    __import__('pkg_resources').run_script('ytmdl==2021.1.14', 'ytmdl')
  File "D:\Users\aech\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "D:\Users\aech\AppData\Local\Programs\Python\Python36\lib\site-packages\pkg_resources\__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\ytmdl-2021.1.14-py3.6.egg\EGG-INFO\scripts\ytmdl", line 456, in <module>
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\ytmdl-2021.1.14-py3.6.egg\EGG-INFO\scripts\ytmdl", line 451, in extract_data
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\ytmdl-2021.1.14-py3.6.egg\EGG-INFO\scripts\ytmdl", line 234, in main
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\ytmdl-2021.1.14-py3.6.egg\ytmdl\core.py", line 109, in download
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\simber\logger.py", line 338, in info
    self._write(message, args, LEVEL_NUMBER)
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\simber\logger.py", line 198, in _write
    self.name
  File "d:\users\aech\appdata\local\programs\python\python36\lib\site-packages\simber\stream.py", line 134, in write
    print(_formatted_out, **params)
  File "D:\Users\aech\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 63-65: character maps to <undefined>`

**Comment by deepjyoti30** [comment]
@eitroo I just tried this on the latest release and it worked all right.

Can you try upgrading to the latest release and upgrade `youtube-dl` as well. That should fix it I guess. Also please post the logs using multiline code block instead of single line.

**Comment by eitroo** [comment]
@deepjyoti30
I've upgraded with:
`pip install ytmdl --upgrade`
`Successfully installed ytmdl-2021.3.4`

However, same error:
` File "D:\Users\aech\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]`
`UnicodeEncodeError: 'charmap' codec can't encode characters in position 63-65: character maps to <undefined>`

**Comment by deepjyoti30** [comment]
@eitroo Thanks for the log. It seems like it is a [simber](https://simber.deepjyoti30.dev) issue. Can you share the version of `simber` you're using? Use the following command:

```console
pip freeze | grep -i simber
```

**Comment by deepjyoti30** [comment]
@eitroo Also, is this happening with all songs that you're trying to download or just this one in particular and others are working all right?

**Comment by eitroo** [comment]
It appears it's just this one song.
This one worked at least https://www.youtube.com/watch?v=x4llqoD2kq8.

**Comment by eitroo** [comment]
@deepjyoti30 
simber            0.2.1
