### ISSUE TITLE
deezer fail download

### ISSUE THREAD

**Issue by Marcioghiraldelli** [deepjyoti30/ytmdl#237]
I'm trying to download a song on deezer and I can't, it always gives the error below.

Traceback (most recent call last):
  File "/usr/local/bin/ytmdl", line 8, in <module>
    sys.exit(entry())
  File "/usr/local/lib/python3.6/site-packages/ytmdl/main.py", line 582, in entry
    extract_data()
  File "/usr/local/lib/python3.6/site-packages/ytmdl/main.py", line 577, in extract_data
    main(args)
  File "/usr/local/lib/python3.6/site-packages/ytmdl/main.py", line 267, in main
    link, yt_title = search(song_name=song_name, args=args)
  File "/usr/local/lib/python3.6/site-packages/ytmdl/core.py", line 87, in search
    temp_data = yt.scan_video(yt.get_href(URL), args.proxy)
  File "/usr/local/lib/python3.6/site-packages/ytmdl/yt.py", line 173, in get_href
    raise ExtractError(url)
ytmdl.exceptions.ExtractError: Couldn't extract data for: https://www.deezer.com/br/track/1805677867

**Comment by Marcioghiraldelli** [comment]
https://www.deezer.com/br/track/1805677867

**Comment by Marcioghiraldelli** [comment]
I'm using centos 7

**Comment by deepjyoti30** [comment]
@Marcioghiraldelli Could you provide the exact command that you run? I understand you tried to download a track but the above information you provided is not much helpful.

I need to know what **exactly** you tried to do and failed.
