### ISSUE TITLE
ytmdl not working on Arch Linux with AUR; Dependency error

### ISSUE THREAD

**Issue by ignition-ctrl** [deepjyoti30/ytmdl#247]
It gives me an error running just `ytmdl`, output below.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (rfc3986 2.0.0 (/usr/lib/python3.10/site-packages), Requirement.parse('rfc3986[idna2008]<2,>=1.3'), {'httpx'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sbin/ytmdl", line 33, in <module>
    sys.exit(load_entry_point('ytmdl==2022.3.16', 'console_scripts', 'ytmdl')())
  File "/sbin/ytmdl", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/ytmdl/__init__.py", line 2, in <module>
    from ytmdl.main import entry
  File "/usr/lib/python3.10/site-packages/ytmdl/main.py", line 34, in <module>
    from ytmdl.core import (
  File "/usr/lib/python3.10/site-packages/ytmdl/core.py", line 7, in <module>
    from ytmdl import (
  File "/usr/lib/python3.10/site-packages/ytmdl/metadata.py", line 3, in <module>
    import itunespy
  File "/usr/lib/python3.10/site-packages/itunespy/__init__.py", line 23, in <module>
    import pycountry
  File "/usr/lib/python3.10/site-packages/pycountry/__init__.py", line 10, in <module>
    import pkg_resources
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3260, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'rfc3986[idna2008]<2,>=1.3' distribution was not found and is required by httpx
```
It seems it's caused by the `httpx` dependency requiring an outdated `rfc3986` version. 
See this issue on the httpx repo: https://github.com/encode/httpx/issues/2169 

## Version Info

- Ytmdl version: 2021.01.13.3.g8c29e79-1
- yt-dlp version: 2022.09.01

## How Ytmdl was installed?
Installed through aur with `yay -S ytmdl-git`

**Comment by deepjyoti30** [comment]
Hey @ignition-ctrl I tried to reproduce the issue, however I was not able to. I was able to succesfully install both `ytmdl` and `ytmdl-git` with `yay`.

Moreover, I officially maintain the `ytmdl` package on AUR so I would suggest you to get that and see if that works. I am not the maintainer of the `ytmdl-git` package so it would be better if you just add a comment in that package so that the maintainer can take a look at it.

**Comment by IncredibleLaser** [comment]
> I was able to succesfully install both `ytmdl` and `ytmdl-git` with yay.

Being able to build and install something with yay or most other AUR helpers doesn't mean the PKGBUILD is valid though, to quote https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot:

> Building in a clean chroot prevents missing dependencies in packages, whether due to unwanted linking or packages missing in the depends array in the PKGBUILD.

`yay` doesn't use a clean environment and as such, successfully building it there doesn't mean the PKGBUILD lists all dependencies. There might be hidden dependencies that just happen to be satisfied on your machine that let the package build successfully. As I commented on the AUR package already, I needed more dependencies added for it to build before, otherwise building failed.

`yay` or by extension a simple `makepkg` building something successfully doesn't mean a PKGBUILD works, but not being able to build with `yay` almost certainly means the PKGBUILD is not correct (though it could also be an issue with the user's installation).

Since you don't maintain the git version, I agree there's nothing you can do for this particular issue, however it's also present in the stable version that you do maintain, and I saw that you didn't include the dependencies I listed in your PKGBUILD, as a result I'm getting the same old errors in a clean chroot again.

I fully understand if you don't want to go through the hassle of setting this up, personally I can only recommend it using the excellent [aurutils](https://github.com/AladW/aurutils) but if you don't, please just take the advice from those who do and include the requirements in the PKGBUILD.

**Comment by deepjyoti30** [comment]
> and I saw that you didn't include the dependencies I listed in your PKGBUILD, as a result I'm getting the same old errors in a clean chroot again.

In the latest release `ytmdl` moved to using `beautifulsoup4` instead of `bs4` so I didn't make any changes in the PKGBUILD to move to `bs4`. Earlier that was an issue because `bs4` was a dependency of `ytmdl`. As such, due to the change in ytmdl's dependency, I decided that the PKGBUILD change would not be required.

Based on your AUR comment, `websockets, brotli and pycryptodomex`. I will update the PKGBUILD to make them direct dependencies of `ytmdl`. I almost forgot about these additions during the last release and thus didn't add them.
