### ISSUE TITLE
ImportError: cannot import name 'NoReturn'

### ISSUE THREAD

**Issue by PolarWinter** [deepjyoti30/ytmdl#252]
# Bug report

## Checklist

- [Y] I have searched for similar bugs in the issues.
- [Y] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2022.3.16.`
- Youtube-dl version: `2022.7.18.`

## How Ytmdl was installed?

Through PIP

## Console Log

```console
PUT LOG HERE. Get the log by running ytmdl in `DEBUG` by `--level DEBUG` flag.
C:\Windows\system32>ytmdl -h
Traceback (most recent call last):
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\tom12\AppData\Local\Programs\Python\Python36\Scripts\ytmdl.exe\__main__.py", line 4, in <module>
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\ytmdl\__init__.py", line 2, in <module>
    from ytmdl.main import entry
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\ytmdl\main.py", line 22, in <module>
    from ytmdl import (
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\ytmdl\yt.py", line 17, in <module>
    from youtubesearchpython import VideosSearch
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\youtubesearchpython\__init__.py", line 1, in <module>
    from youtubesearchpython.search import Search, VideosSearch, ChannelsSearch, PlaylistsSearch, CustomSearch, ChannelSearch
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\youtubesearchpython\search.py", line 1, in <module>
    from youtubesearchpython.core.constants import *
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\youtubesearchpython\core\__init__.py", line 1, in <module>
    from .video import VideoCore
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\youtubesearchpython\core\video.py", line 7, in <module>
    from youtubesearchpython.core.requests import RequestCore
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\youtubesearchpython\core\requests.py", line 1, in <module>
    import httpx
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\httpx\__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\httpx\_api.py", line 4, in <module>
    from ._client import Client
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\httpx\_client.py", line 9, in <module>
    from ._auth import Auth, BasicAuth, FunctionAuth
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\httpx\_auth.py", line 10, in <module>
    from ._models import Request, Response
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\httpx\_models.py", line 16, in <module>
    from ._content import ByteStream, UnattachedStream, encode_request, encode_response
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\httpx\_content.py", line 17, in <module>
    from ._multipart import MultipartStream
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\httpx\_multipart.py", line 14, in <module>
    from ._utils import (
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\httpx\_utils.py", line 13, in <module>
    import sniffio
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\sniffio\__init__.py", line 10, in <module>
    from ._impl import (
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\sniffio\_impl.py", line 1, in <module>
    from contextvars import ContextVar
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\contextvars\__init__.py", line 4, in <module>
    import immutables
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\immutables\__init__.py", line 18, in <module>
    from ._protocols import MapKeys as MapKeys
  File "c:\users\tom12\appdata\local\programs\python\python36\lib\site-packages\immutables\_protocols.py", line 6, in <module>
    from typing import NoReturn
ImportError: cannot import name 'NoReturn'
```

## Description

No matter what I type in after ytmdl it always comes up with "ImportError: cannot import name 'NoReturn'"

**Comment by deepjyoti30** [comment]
Hey @PolarWinter this is not exactly a `ytmdl` issue. Looking through the web indicates that the version of `python` you are using is not enough.

This should have been enforced by the library that is actually using the `NoReturn` keyword which is the `youtubesearchpython` library.

Anyhow, you can upgrade your python to `3.6.2` or later in order for this error to go away.  As a safe bet, I will update the python version required for `ytmdl` to `3.6.2` or above.

Thanks for reporting the issue!
