### ISSUE TITLE
Unable to download playlists

### ISSUE THREAD

**Issue by drmdarsh09** [deepjyoti30/ytmdl#253]
I have been trying to input and download a playlist but I'm getting the following result. I have tried multiple playists
` ==> Youtube playlist passed...extracting!
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Scripts\ytmdl.exe\__main__.py", line 7, in <module>
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\ytmdl\main.py", line 582, in entry
    extract_data()
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\ytmdl\main.py", line 557, in extract_data
    logger.info("Playlist: {}".format(playlist_name))
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\simber\logger.py", line 366, in info
    self._write(message, args, LEVEL_NUMBER)
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\simber\logger.py", line 203, in _write
    stream.write(
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\simber\stream.py", line 138, in write
    print(_formatted_out, **params)
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001faa9' in position 42: character maps to <undefined>`

**Comment by deepjyoti30** [comment]
@drmdarsh09 Thanks for the bug. This issue looks like it is the same as #240 which is already a known bug that is being worked on.

I will close this issue and you can track the status on the other issue.
