### ISSUE TITLE
Can't download music with proxy setting.

### ISSUE THREAD

**Issue by gb0519** [deepjyoti30/ytmdl#259]
# Bug report

## Checklist

- [1] I have searched for similar bugs in the issues.
- [1] I will add the bug label to this issue.

## Version Info

- Ytmdl version: `2022.12.25`
- Youtube-dl version: `PUT VERSION HERE`

## How Ytmdl was installed?

install by pip

## Console Log

 ==> Logger running in DEBUG mode 
 ==> Passed args: Namespace(SONG_NAME=['https://www.youtube.com/playlist?list=PLIpKgNUjeGsbRfoc6YJkmd5uP5cRSttHM'], quiet=False, output_dir=None, song=None, choice=None, artist=None, album=None, disable_metaadd=False, skip_meta=False, manual_meta=False, itunes_id=None, spotify_id=None, disable_sort=False, ask_meta_name=False, on_meta_error=None, proxy='********', url=None, list=None, nolocal=False, format='mp3', trim=False, get_opts=False, keep_chapter_name=False, download_archive=None, ignore_chapters=False, ytdl_config=None, dont_transcode=False, pl_start=None, pl_end=None, pl_items=None, ignore_errors=False, title_as_name=False, level='DEBUG', disable_file=False, list_level=False) 
 ==> on_meta_error before:  None
 ==> on_meta_error after:  exit
 ==> itunes_country: US
 ==> Youtube playlist passed...extracting! 
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLIpKgNUjeGsbRfoc6YJkmd5uP5cRSttHM
[youtube:tab] PLIpKgNUjeGsbRfoc6YJkmd5uP5cRSttHM: Downloading webpage
[youtube:tab] PLIpKgNUjeGsbRfoc6YJkmd5uP5cRSttHM: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: 歌曲
[youtube:tab] Playlist 歌曲: Downloading 2 items of 2
[download] Downloading item 1 of 2
[download] Downloading item 2 of 2
[download] Finished downloading playlist: 歌曲
 ==> Playlist: 歌曲 
 ==> 2 songs found 
 ==> [] 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fa4703be5b0>, 'Connection to music.youtube.com timed out. (connect timeout=30)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='music.youtube.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4703be5b0>, 'Connection to music.youtube.com timed out. (connect timeout=30)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/ytmdl", line 8, in <module>
    sys.exit(entry())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/main.py", line 610, in entry
    extract_data()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/main.py", line 603, in extract_data
    main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/main.py", line 235, in main
    song_name, verify_name = extract_song_name(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/main.py", line 526, in extract_song_name
    song_name, verify_title = yt.get_title(args.url, args.ytdl_config)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/yt.py", line 395, in get_title
    title = get_title_from_ytmusic(extract_video_id(url=url))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/utils/ytmusic.py", line 26, in get_title_from_ytmusic
    ytmusic = YTMusic()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 99, in __init__
    self.headers.update(get_visitor_id(self._send_get_request))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmusicapi/helpers.py", line 34, in get_visitor_id
    response = request_func(YTM_DOMAIN)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 148, in _send_get_request
    response = self._session.get(url,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='music.youtube.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fa4703be5b0>, 'Connection to music.youtube.com timed out. (connect timeout=30)'))

## Description
It seems that ytmdl can extract the playlist with proxy setting, there are two songs in the playlist.
But it failed to download these two songs. The playlist is public, you can test with it.

My input:

ytmdl --proxy "socks5://*****:***" "https://www.youtube.com/playlist?list=PLIpKgNUjeGsbRfoc6YJkmd5uP5cRSttHM"

output:

==> Youtube playlist passed...extracting! 
 ==> Playlist: 歌曲 
 ==> 2 songs found 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7fb141b2ea30>, 'Connection to music.youtube.com timed out. (connect timeout=30)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='music.youtube.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb141b2ea30>, 'Connection to music.youtube.com timed out. (connect timeout=30)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/ytmdl", line 8, in <module>
    sys.exit(entry())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/main.py", line 610, in entry
    extract_data()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/main.py", line 603, in extract_data
    main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/main.py", line 235, in main
    song_name, verify_name = extract_song_name(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/main.py", line 526, in extract_song_name
    song_name, verify_title = yt.get_title(args.url, args.ytdl_config)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/yt.py", line 395, in get_title
    title = get_title_from_ytmusic(extract_video_id(url=url))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmdl/utils/ytmusic.py", line 26, in get_title_from_ytmusic
    ytmusic = YTMusic()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 99, in __init__
    self.headers.update(get_visitor_id(self._send_get_request))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmusicapi/helpers.py", line 34, in get_visitor_id
    response = request_func(YTM_DOMAIN)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ytmusicapi/ytmusic.py", line 148, in _send_get_request
    response = self._session.get(url,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='music.youtube.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb141b2ea30>, 'Connection to music.youtube.com timed out. (connect timeout=30)'))

**Comment by deepjyoti30** [comment]
This feature might have become outdated since we migrated to `yt-dlp` from `youtube-dl`. I'll keep this as a bug.

The bigger issue that I faced here was testing it with some proxy which never seemed to work for me thus I could not vouch for it's stability by myself.
