### ISSUE TITLE
Can't install via pip with git

### ISSUE THREAD

**Issue by loulou310** [deepjyoti30/ytmdl#263]
# Bug report

## Checklist

- [x] I have searched for similar bugs in the issues.
- [x] I will add the bug label to this issue.

## Version Info

- Ytmdl version:  a9251c8e047eca64649b70821c81bb33c5895183
- Youtube-dl version: `none`
- Python version : `3.11.0` from Chocolatey

## How Ytmdl was installed?

Via the command `pip install git+https://github.com/deepjyoti30/ytmdl.git`

## Console Log

```console
Collecting git+https://github.com/deepjyoti30/ytmdl.git
  Cloning https://github.com/deepjyoti30/ytmdl.git to c:\users\user\appdata\local\temp\pip-req-build-1k5jzz9l
  Running command git clone --filter=blob:none --quiet https://github.com/deepjyoti30/ytmdl.git 'C:\Users\User\AppData\Local\Temp\pip-req-build-1k5jzz9l'
  Resolved https://github.com/deepjyoti30/ytmdl.git to commit a9251c8e047eca64649b70821c81bb33c5895183
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      C:\Users\User\AppData\Local\Temp\pip-req-build-1k5jzz9l\setup.py:50: UserWarning: ytmdl.bash does not exist, skipping.
        warn("%s does not exist, skipping." % filename)
      C:\Users\User\AppData\Local\Temp\pip-req-build-1k5jzz9l\setup.py:50: UserWarning: ytmdl.zsh does not exist, skipping.
        warn("%s does not exist, skipping." % filename)
      C:\Python311\Lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
      WARNING: The wheel package is not available.
        error: subprocess-exited-with-error

        python setup.py bdist_wheel did not run successfully.
        exit code: 1

        [6 lines of output]
        usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
           or: setup.py --help [cmd1 cmd2 ...]
           or: setup.py --help-commands
           or: setup.py cmd --help

        error: invalid command 'bdist_wheel'
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pyDes
      ERROR: Failed to build one or more wheels
      Traceback (most recent call last):
        File "C:\Python311\Lib\site-packages\setuptools\installer.py", line 82, in fetch_build_egg
          subprocess.check_call(cmd)
        File "C:\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Python311\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpb0q1xcpl', '--quiet', 'pyDes']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-req-build-1k5jzz9l\setup.py", line 60, in <module>
          setuptools.setup(
        File "C:\Python311\Lib\site-packages\setuptools\__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "C:\Python311\Lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Python311\Lib\site-packages\setuptools\dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\site-packages\setuptools\dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\site-packages\setuptools\installer.py", line 84, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['C:\\Python311\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpb0q1xcpl', '--quiet', 'pyDes']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

## Description

Was installing the module thru pip with git but it failed, see above output. The issue can't be reproduced by using `python3 setup.py install.`

**Comment by deepjyoti30** [comment]
I am not sure how pip works when installations are done from git but it seems like it is trying to install all the packages (including dependencies).

As the error indicates, the issue is with building `pyDes` because `bdist_wheel` is an unrecognized param for `setup.py`.

As a workaround, you can try cloning the repo and installing using:

```console
python3 setup.py install
```

**Comment by loulou310** [comment]
That's what I went with
