### ISSUE TITLE
too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by fedya** [deepjyoti30/ytmdl#36]
```
[omv@e964bd87a56f ytmdl]$ /usr/bin/ytmdl 'excavation the haxan cloak'
 ==> Searching to see if already present in /home/omv/ytmdl
 ==> Searching Youtube for excavation the haxan cloak
 ==> Choose One
 [1] The Haxan Cloak - Excavation (Part 1 & 2) by ADDA with dur 12:19
 [2] The Haxan Cloak - Excavation ALBUM REVIEW by theneedledrop with dur 6:42
 [3] Excavation (Part 1) by The Haxan Cloak - Topic with dur 8:10
 [4] The Haxan Cloak - Excavation (Part 1) by Pleasurable Pain with dur 8:10
 [5] Mix - The Haxan Cloak - Excavation (Part 1 & 2) by The Haxan Cloak - Excavation (Part 1 & 2) with dur Playlist
 [0] More results
 ==> Enter Choice [a valid choice] 1
 ==> Downloading The Haxan Cloak - Excavation (Part 1 & 2) in 320kbps
 ==> Saving the files to: /home/omv/.cache/ytmdl
Size: 6 MB
Saving as: /home/omv/.cache/ytmdl/The#Haxan#Cloak#-#Excavation#(Part#1#&#2).mp3
ERROR: too many values to unpack (expected 2)
 ==> Downloaded!
 ==> Converting to mp3...
Traceback (most recent call last):
  File "/usr/bin/ytmdl", line 4, in <module>
    __import__('pkg_resources').run_script('ytmdl==2019.11.15.post3', 'ytmdl')
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.7/site-packages/ytmdl-2019.11.15.post3-py3.7.egg/EGG-INFO/scripts/ytmdl", line 230, in <module>
  File "/usr/lib/python3.7/site-packages/ytmdl-2019.11.15.post3-py3.7.egg/EGG-INFO/scripts/ytmdl", line 225, in extract_data
  File "/usr/lib/python3.7/site-packages/ytmdl-2019.11.15.post3-py3.7.egg/EGG-INFO/scripts/ytmdl", line 172, in main
  File "/usr/lib/python3.7/site-packages/ytmdl-2019.11.15.post3-py3.7.egg/ytmdl/utility.py", line 52, in convert_to_mp3
AttributeError: module 'ffmpeg' has no attribute 'input'

```

**Comment by deepjyoti30** [comment]
@fedya The fffmpeg issue should be fixed in the last commit. Sorry about that. Thanks for raising the issue.

**Comment by fedya** [comment]
i make git pull
and run it again

```
[omv@e964bd87a56f ytmdl]$ ./bin/ytmdl 'miste'
/home/omv/.cache/ytmdl/logs/log.cat
 ==> Searching to see if already present in /home/omv/ytmdl
 ==> Searching Youtube for miste
 ==> Choose One
 [1] Mr Bean in Room 426 | Episode 8 | Widescreen Version | Classic Mr Bean by Classic Mr Bean with dur 24:57
 [2] Mr Bean Cartoon 2018 | Mr Bean Animated Series Long Compilation #2 by Cartoons for Kids with dur 30:17
 [3] The Haxan Cloak - Miste by Francesca Sturzi with dur 5:38
 [4] How to make Chom Chom || চম চম || Bangladeshi Miste Recipe by Fatemas Dream kitchen with dur 4:32
 [5] Mr. Bean Rides Again | Episode 6 | Mr. Bean Official by Mr Bean with dur MrBean
 [0] More results
 ==> Enter Choice [a valid choice] 1
 ==> Downloading Mr Bean in Room 426 | Episode 8 | Widescreen Version | Classic Mr Bean in 320kbps
 ==> Saving the files to: /home/omv/.cache/ytmdl
Size: 11 MB
Saving as: /home/omv/.cache/ytmdl/Mr#Bean#in#Room#426#|#Episode#8#|#Widescreen#Version#|#Classic#Mr#Bean.mp3
ERROR: too many values to unpack (expected 2)
 ==> ERROR: exceptions must derive from BaseException

```

looks same

**Comment by deepjyoti30** [comment]
Hey @fedya Did you install again after cloning the latest commits? Seems like the logger is running in DEBUG mode, that shouldn't happen.
