### ISSUE TITLE
Running ytmdl with no arguments fails

### ISSUE THREAD

**Issue by ELChris414** [deepjyoti30/ytmdl#40]
Title describes it, running `ytmdl` gives this error:

EDIT: I'm sorry if this is something once again caused by leftovers of my previous installation, I've done my best to clean it up and be in sync only with github.
```
Traceback (most recent call last):
  File "/usr/local/bin/ytmdl", line 4, in <module>
    __import__('pkg_resources').run_script('ytmdl==2019.11.15.post3', 'ytmdl')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/ytmdl-2019.11.15.post3-py3.7.egg/EGG-INFO/scripts/ytmdl", line 254, in <module>
  File "/usr/local/lib/python3.7/dist-packages/ytmdl-2019.11.15.post3-py3.7.egg/EGG-INFO/scripts/ytmdl", line 249, in extract_data
  File "/usr/local/lib/python3.7/dist-packages/ytmdl-2019.11.15.post3-py3.7.egg/EGG-INFO/scripts/ytmdl", line 96, in main
IndexError: list index out of range
```

**Comment by deepjyoti30** [comment]
@ELChris414 No need to be sorry. It was due to the recent changes. I fixed it in the latest commit.

**Comment by deepjyoti30** [comment]
Should be fixed in the next release
