### ISSUE TITLE
Fedora 31 can't launch / use ytmdl

### ISSUE THREAD

**Issue by thekabal** [deepjyoti30/ytmdl#43]
**pip3 install style:**
Requirement already satisfied: ytmdl in /usr/local/lib/python3.7/site-packages (2019.11.15)
Requirement already satisfied: youtube_dl in /usr/lib/python3.7/site-packages (from ytmdl) (2019.11.28)
Requirement already satisfied: mutagen in /usr/local/lib/python3.7/site-packages (from ytmdl) (1.43.0)
Requirement already satisfied: itunespy in /usr/local/lib/python3.7/site-packages (from ytmdl) (1.5.5)
Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (from ytmdl) (2.22.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.7/site-packages (from ytmdl) (0.4.3)
Requirement already satisfied: bs4 in /usr/local/lib/python3.7/site-packages (from ytmdl) (0.0.1)
Requirement already satisfied: downloader-cli in /usr/local/lib/python3.7/site-packages (from ytmdl) (0.1.0.post2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests->ytmdl) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3.7/site-packages (from requests->ytmdl) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.7/site-packages (from requests->ytmdl) (1.25.7)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/site-packages (from bs4->ytmdl) (4.8.2)
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python3.7/site-packages (from beautifulsoup4->bs4->ytmdl) (1.9.5)

Standard user install style from git clone:
**$ sudo python3 setup.py install**
WARNING: The wheel package is not available.
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-wheel-ldmwv1oe/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-741ytlj7:
  ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for future
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpcggwfv51', '--quiet', 'future']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 43, in <module>
    setup_requires=req_pkgs
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpcggwfv51', '--quiet', 'future']' returned non-zero exit status 1.

FFMpeg is installed:
$ rpm -qa | grep -i ffmp
ffmpeg-4.2.1-3.fc31.x86_64
ffmpeg-devel-4.2.1-3.fc31.x86_64
ffmpeg-libs-4.2.1-3.fc31.x86_64
compat-ffmpeg28-2.8.15-4.fc31.x86_64

**Current "which"/default ytmdl also fails:**
/usr/local/bin/ytmdl money in the

 ==> Traceback (most recent call last):
  File "/usr/local/bin/ytmdl", line 4, in <module>
    __import__('pkg_resources').run_script('ytmdl==2019.11.15.post3', 'ytmdl')
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/site-packages/ytmdl-2019.11.15.post3-py3.7.egg/EGG-INFO/scripts/ytmdl", line 255, in <module>
  File "/usr/local/lib/python3.7/site-packages/ytmdl-2019.11.15.post3-py3.7.egg/EGG-INFO/scripts/ytmdl", line 250, in extract_data
  File "/usr/local/lib/python3.7/site-packages/ytmdl-2019.11.15.post3-py3.7.egg/EGG-INFO/scripts/ytmdl", line 111, in main
  File "/usr/local/lib/python3.7/site-packages/ytmdl-2019.11.15.post3-py3.7.egg/ytmdl/cache.py", line 88, in main
  File "/usr/local/lib/python3.7/site-packages/ytmdl-2019.11.15.post3-py3.7.egg/ytmdl/cache.py", line 58, in search
  File "/usr/local/lib/python3.7/site-packages/ytmdl-2019.11.15.post3-py3.7.egg/ytmdl/logger.py", line 95, in info
  File "/usr/local/lib/python3.7/site-packages/ytmdl-2019.11.15.post3-py3.7.egg/ytmdl/logger.py", line 51, in _write
TypeError: expected str, bytes or os.PathLike object, not PosixPath

**Comment by thekabal** [comment]
Sorry for the inconsistent bold/formatting. It seems markdown is triggering on some of the code snippets.

The summary is that on my Fedora 31 system, I can't seem to get ytmdl working correctly. Any suggestions are appreciated.

**Comment by deepjyoti30** [comment]
Hey @thekabal , apologies for the later reply.

Seems like something got screwed up while installation.

Can you please uninstall ytmdl by ```sudo pip uninstall ytmdl```

After that, remove all the folder/files related to ```ytmdl``` from the ```/usr/local/lib/python3.7/site-packages/```.

Make sure it's not installed anywhere, try running the above uninstall command once more and cross check the above dir for any file left.

After doing all the above, install the latest version from Pypi using ```sudo pip install ytmdl --no-cache-dir```

After all of this is done, try running ytmdl and report if you get the ```PosixPath``` error again.
