### ISSUE TITLE
unable to use in wsl 

### ISSUE THREAD

**Issue by satyamisme** [deepjyoti30/ytmdl#65]
ImportError: No module named pathlib
root@Genesis:/mnt/c/Users/Genesis/Desktop/ytmdl# sudo ytmdl samajavaragamana-female
Traceback (most recent call last):
  File "/usr/local/bin/ytmdl", line 4, in <module>
    __import__('pkg_resources').run_script('ytmdl==2020.3.21', 'ytmdl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ytmdl-2020.3.21-py2.7.egg/EGG-INFO/scripts/ytmdl", line 19, in <module>

  File "build/bdist.linux-x86_64/egg/ytmdl/dir.py", line 6, in <module>
  File "build/bdist.linux-x86_64/egg/ytmdl/defaults.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/ytmdl/setupConfig.py", line 5, in <module>
  File "build/bdist.linux-x86_64/egg/ytmdl/logger.py", line 2, in <module>
ImportError: No module named pathlib
root@Genesis:/mnt/c/Users/Genesis/Desktop/ytmdl#

**Comment by deepjyoti30** [comment]
Hey @satyamisme did you try installing pathlib manually. It's not added as a dependency at the moment because I assumed it was pre installed Python is installed.

Anyway, try installing pathlib using ```pip install pathlib```.

Try to run after doing above and report back if you face some other issue. Another user was able to use ```ytmdl``` succesfully on their WSL running machine so your issue seems more like user specific.

**Comment by satyamisme** [comment]
thank you ymtdl gui vesion is working perfectly

**Comment by deepjyoti30** [comment]
@satyamisme I'm sorry but what do you mean by "gui version"? As far as I know there is no GUI version of ```ytmdl```.
