### ISSUE TITLE
UI: Menus not fault tolerant

### ISSUE THREAD

**Issue by jepace** [deepjyoti30/ytmdl#89]
The menu / input system handles invalid input by crashing:
 
==> Enter Choice [a valid choice]  [I hit enter]
Traceback (most recent call last):
  File "/home/jepace/.local/bin/ytmdl", line 434, in <module>
    extract_data()
  File "/home/jepace/.local/bin/ytmdl", line 429, in extract_data
    main(args)
  File "/home/jepace/.local/bin/ytmdl", line 290, in main
    choice = song.getChoice(data, 'mp3')
  File "/home/jepace/.local/lib/python3.6/site-packages/ytmdl/song.py", line 126, in getChoice
    choice = int(choice)
ValueError: invalid literal for int() with base 10: ''

Maybe it needs some error handling for inputs?

**Comment by danimateo** [comment]
Check [my](https://github.com/deepjyoti30/ytmdl/pull/85) pull request. I added a default for this and other stuff.
